# Default values for logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
policy_namespace: open-cluster-policies
nmstate:
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    channel: stable
    installPlanApproval: Automatic
    source: redhat-operators
    sourceNamespace: openshift-marketplace

# Labels
# autoshift.io/nmstate<bool>: If not set the Kubernetes NMState Operator will not be managed. default false
# autoshift.io/nmstate-nncp-{{ some string }}<String>: Filename of NMState config that exists in files. Can be specified multiple times to apply more than one config to a cluster, they must have unique labels but start with 'autoshift.io/nmstate-nncp-'. default absent
# autoshift.io/nmstate-channel<String>: default stable
# autoshift.io/nmstate-install-plan-approval<String>: default Automatic
# autoshift.io/nmstate-source<String>: default redhat-operators
# autoshift.io/nmstate-source-namespace<String>: default openshift-marketplace
