apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: managed-clusters-gitops
  namespace: {{ .Values.acm.gitops_namespace | default "openshift-gitops"}}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  clusterSet: managed