kind: ManagedClusterSet
apiVersion: clusterview.open-cluster-management.io/v1beta2
metadata:
  name: managed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  clusterSelector:
    selectorType: ExclusiveClusterSetLabel
